[workspace]
members = [
    "crates/stablebond-types",
    "programs/stablebond-core",
    "programs/stablebond-yield",
]
resolver = "2"

[workspace.dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
anchor-spl = "0.32.1"

[profile.release]
overflow-checks = true
